version: '3.7'
services:
        web:
                build: .
                command: python /code_django/manage.py runserver 0.0.0.0:8000
                volumes:
                        - .:/code_django
                ports:
                        - 8000:8000
                depends_on:
                        - db

        db:
                image: postgres:12
                volumes:
                        - postgres_data:/var/lib/postgresql/data
                ports:
                        - 5432:5432
                environment:
                        POSTGRES_DB: "postgres"
                        POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
        postgres_data: 

